homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name="loginpage"),
    path('logout', views.logout, name="logout"),
    path('signup', views.signup, name="signup"),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login as login_auth, logout as logout_auth

# source :https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html


# Create your views here.
def index(request):
    user = request.user
    if user.is_authenticated:
        return render(request, 'welcome.html')        
    else:
        return render(request, 'index.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login_auth(request, user)
            return redirect('homepage:index')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def login(request):
    user = request.user
    login_form = AuthenticationForm()
    
    if user.is_authenticated:
        return redirect('homepage:index')

    if request.method == "POST":
        login_form = AuthenticationForm(data = request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login_auth(request, user)
            return redirect('homepage:index')
    return render(request, 'loginpage.html', {'form':login_form})

def logout(request):
    if request.method == 'POST':
        logout_auth(request)
    return redirect('homepage:index')

homepage/templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title> Story 9 Homepage </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href = "{% static 'css/bootstrap.css' %}" rel = "stylesheet">
    <link href = "{% static 'css/style.css' %}" rel = "stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body>
<br>
<br>
    
    <div class="container">
        <div class="row">
          <div class="col-sm">
            <h2> Welcome to our page </h2>
            <a href="login">
              <button>Click Here to Login</button>
            </a>
            <br>
            or
            <br>
            <a href="signup">
              <button>Click Here to Signup</button>
            </a>
          </div>
        </div>
    </div>

</body>
</html>

homepage/templates/loginpage.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href = "{% static 'css/bootstrap.css' %}" rel = "stylesheet">
    <link href = "{% static 'css/style.css' %}" rel = "stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body>
<br>
<br>
    
    <div class="container">
        <div class="row">
          <div class="col-sm">
            <div class="form">
                <form action="{% url 'homepage:loginpage' %}" method="POST">
                    {% csrf_token %}
                    <div><p>Username</p>{{ form.username }}</div>
                    <br>
                    <div><p>Password</p>{{ form.password }}</div>
                    <br>
                    <div>
                        <button type="submit" class="formbutton">Login</button>
                    </div>
                </form>
            </div>
          </div>
        </div>
        <br>
        <br>
    </div>

</body>
</html>

homepage/templates/signup.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href = "{% static 'css/bootstrap.css' %}" rel = "stylesheet">
    <link href = "{% static 'css/style.css' %}" rel = "stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body>
<br>
<br>
    
    <div class="container">
        <div class="row">
          <div class="col-sm">
              <h2>Sign up</h2>
              <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Sign up</button>
              </form>
          </div>
        </div>
        <br>
        <br>
    </div>

</body>
</html>

homepage/templates/welcome.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title> Welcome </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href = "{% static 'css/bootstrap.css' %}" rel = "stylesheet">
    <link href = "{% static 'css/style.css' %}" rel = "stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body>
<br>
<br>
    
    <div class="container">
        <div class="row">
          <div class="col-sm">
                <h2>Welcome, {{ user.username }}! have a good day</h2>
                If you want to logout, click the button below
                <br>
                You will be redirected to the homepage
                <form action="{% url 'homepage:logout' %}" method="POST">
                        {% csrf_token %}
                        <div>
                            <button type="submit" class="formbutton">Logout</button>
                        </div>
                </form>

          </div>
        </div>
    </div>

</body>
</html>